services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 8090:8090 # port for qbittorrent
    volumes:
      - /volume1/Docker/gluetun:/gluetun
    environment:
      - PUID=1000 # CHANGE_TO_YOUR_UID
      - PGID=1000 # CHANGE_TO_YOUR_GID
      - TZ=America/Denver # CHANGE_TO_YOUR_TZ
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=ol3siqvDFyuRMOl4z9r0gSG5YlKIsWpIpsQ/POOLo2A=
      - WIREGUARD_ADDRESSES=10.69.132.122/32
      - SERVER_COUNTRIES=USA
    labels:
      - com.centurylinklabs.watchtower.enable=false
    restart: unless-stopped

  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000 # CHANGE_TO_YOUR_UID
      - PGID=1000 # CHANGE_TO_YOUR_GID
      - TZ=America/Denver # CHANGE_TO_YOUR_TZ
      - WEBUI_PORT=8090
    volumes:
      - /volume1/Docker/qbittorrent:/config
      - /volume1/Downloads:/downloads
      - /volume2/SSD_Downloads:/ssd # Use SSD folder for initial downloads
    network_mode: "container:gluetun"
    depends_on:
      - gluetun
    restart: unless-stopped
