version: '3.8'

services:
  gluetun:
    image: qmcgaw/gluetun:latest
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp
      - 8388:8388/tcp
      - 8388:8388/udp
      - "192.168.1.51:8088:8088" # Forward port 8088 to qBittorrent container
    volumes:
      - /Docker/Gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=openvpn
      - OPENVPN_USER=0305266735298883
      - OPENVPN_PASSWORD=m
      - TZ=America/Denver
      - LOG_LEVEL=info
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
      - WEBUI_PORT=8088
    volumes:
      - "/Docker/Qbit/Config:/config"
      - "/Storage/Downloads:/downloads"
    depends_on:
      - gluetun
    network_mode: "service:gluetun"  # Set the network mode to use the network stack of gluetun
